name: Build and run tests
run-name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.23-bookworm
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: make setup
      - run: make install

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5

      - run: make test
      - run: make enforce
      - run: make coveralls

    services:
      redis:
        image: redis

